options {
  IGNORE_CASE=false;
}

PARSER_BEGIN(simplejava)

public class simplejava {
}


PARSER_END(simplejava)

TOKEN_MGR_DECLS :
{
    public static int numcomments = 0;
}

SKIP :
{
    < "//" > : INLINE_COMMENT
|   < " " >
|   < "\n" >
|   < "\t" >
}

SKIP :
{
< "/*" > {numcomments++;}: IN_MULTI_LINE_COMMENT
}

<IN_MULTI_LINE_COMMENT>
SKIP :
{
    < " " >
|   < "/*"> {numcomments++;}
|   < "*/" > {numcomments--; if(numcomments == 0) SwitchTo(DEFAULT);}
|   < ~[] >
}

<INLINE_COMMENT>
SKIP :
{
    <"\n"> : DEFAULT
|   < ~[] >
}

TOKEN :
{
    <INTEGER_LITERAL: (["0"-"9"])+>
|   < DO: "do">
|   < ELSE: "else">
|   < FALSE: "false">
|   < FOR: "for">
|   < IF: "if">
|   < TRUE: "true">
|   < WHILE: "while">
|   < RETURN: "return">
|   < PLUS_EQUALS: "+=">
|   < NOT_EQUALS: "!=">
|   < EQUALS_EQUALS: "==">
|   < LESS_THAN_EQUAL_TO: "<=">
|   < GREATER_THAN_EQUAL_TO: ">=">
|   < PLUS_PLUS: "++">
|   < MINUS_MINUS: "--">
|   < AND: "&&">
|   < OR: "||">
|   <IDENTIFIER: ["a"-"z", "A"-"Z"](["a"-"z", "A"-"Z","0"-"9", "_"])*>
}

TOKEN :
{
    < EQUALS: "=" >
|   < PLUS: "+" >
|   < MINUS: "-" >
|   < ASTERISK: "*" >
|   < SLASH: "/" >
|   < LEFT_PARENTHESIS: "(">
|   < RIGHT_PARENTHESIS: ")">
|   < LEFT_BRACE: "{">
|   < RIGHT_BRACE: "}">
|   < LEFT_BRACKET: "[">
|   < RIGHT_BRACKET: "]">
|   < PERIOD: ".">
|   < COMMA: ",">
|   < SEMICOLON: ";">
|   < LESS_THAN: "<">
|   < GREATER_THAN: ">">
|   < NOT: "!">
}


void program():
{}
{
    (s())*
    <EOF>
}

void s():
{}
{
    header() (class_decl() | params() (class_decl() | <SEMICOLON> ))
}

//class foo{stuff}
void class_decl():
{}
{
    <LEFT_BRACE> block()
}

void header():
{}
{
    <IDENTIFIER> <IDENTIFIER>
}

//Series of 0 or more arguments
void params():
{}
{
    <LEFT_PARENTHESIS>  arg()
}

void arg():
{}
{
    LOOKAHEAD(2) header() arg()
|   expression() (LOOKAHEAD(2) complex())* arg()
|   <LEFT_BRACKET> (var())? (LOOKAHEAD(2) args_p())* <RIGHT_BRACKET> arg()
|   <RIGHT_PARENTHESIS>
|   <COMMA> arg()
}


//Defines everything between two braces of a function or class
void block():
{}
{
    (statement())* <RIGHT_BRACE>
}

void statement():
{}
{
    <LEFT_BRACE> block()
|   <DO>
|   LHS()
|   iff()
|   <FOR> <LEFT_PARENTHESIS> forr()
|   while_block()
|   returnn()
}

void returnn():
{}
{
    <RETURN> RHS_prime()
}

void while_block():
{}
{
    <WHILE> <LEFT_PARENTHESIS> bool() <RIGHT_PARENTHESIS>
}

void forr():
{}
{
    <RIGHT_PARENTHESIS>
|   for_prime()
}

void for_prime():
{}
{
    <SEMICOLON> for_prime()
|   expression() forr()
|   (<PLUS_PLUS> | <MINUS_MINUS>) forr()
|   (<GREATER_THAN> | <LESS_THAN> | <EQUALS> RHS_prime()) forr()
}

void iff():
{}
{
    <IF> <LEFT_PARENTHESIS> bool() <RIGHT_PARENTHESIS>
|   <ELSE>
}

void bool():
{}
{
    LOOKAHEAD(3) <IDENTIFIER> (LOOKAHEAD(2) <LEFT_BRACKET>(ex())?<RIGHT_BRACKET>)+ (LOOKAHEAD(2) args_p())* (bool_prime())?  {System.out.println("entered bool_args()");}
|   LOOKAHEAD(3) ex() (LOOKAHEAD(2) bool_prime())?    {System.out.println("entered ex()");}
|   LOOKAHEAD(3) var() (LOOKAHEAD(2) bool_prime())?   {System.out.println("entered var() bool_prime()");}
|   LOOKAHEAD(3) function_call() (LOOKAHEAD(2) bool_prime())?   {System.out.println("entered func");}
|   bool_prime() {System.out.println("entered bool_prime()");}
}

void function_call():
{}
{
    (<NOT>)? <IDENTIFIER> params()
}

void ex():
{}
{
    LOOKAHEAD(3) args() (LOOKAHEAD(2) ex_p())? {System.out.println("entered args ex()");}
|   LOOKAHEAD(3) (<NOT>)? <IDENTIFIER> params() (LOOKAHEAD(2) ex_p())? {System.out.println("entered params");}
|   LOOKAHEAD(3) var() (LOOKAHEAD(2) ex_p())? {System.out.println("entered var ex()");}
|   ex_p() {System.out.println("entered ex_p()");}
}

void ex_p():
{}
{
    LOOKAHEAD(2) expression_ops() (LOOKAHEAD(2) var() | args())
|   expression_ops() ex()
|   <LEFT_PARENTHESIS> ex() <RIGHT_PARENTHESIS> (LOOKAHEAD(2) ex_p())?
}

void expression_ops():
{}
{
    (<PLUS> | <MINUS> | <ASTERISK> | <SLASH> | <AND> | <OR>
    | <LESS_THAN_EQUAL_TO>
    | <GREATER_THAN_EQUAL_TO>
    | <LESS_THAN>
    | <NOT_EQUALS>
    | <GREATER_THAN>
    | <EQUALS_EQUALS>)
}

void args():
{}
{
    <IDENTIFIER> (LOOKAHEAD(2) <LEFT_BRACKET>(ex())?<RIGHT_BRACKET>)+ (LOOKAHEAD(2) args_p())* {System.out.println("entered args()");}
}

void args_p():
{}
{
    <PERIOD> (LOOKAHEAD(2) args() | <IDENTIFIER>) {System.out.println("entered args_p()");}
}

void bool_prime():
{}
{
    (<AND> | <OR> | <GREATER_THAN> | <LESS_THAN> | <GREATER_THAN_EQUAL_TO> | <LESS_THAN_EQUAL_TO>
    | <EQUALS_EQUALS> | <NOT_EQUALS> ) (LOOKAHEAD(3) bool() | (ex() bool_prime()))
}

void LHS():
{}
{
    //this will bite me later just watch
    <SEMICOLON>
|   var() LHS_prime()
}

void LHS_prime():
{}
{
    var() LHS_prime()
|   complex() LHS_prime()
|   RHS() {System.out.println("entered rhs()");}
}

void RHS():
{}
{
    <SEMICOLON>
|   <EQUALS> RHS_prime()
}

void RHS_prime():
{}
{

    LOOKAHEAD(2) (<PLUS> | <MINUS> | <ASTERISK> | <SLASH> | <AND> | <OR>
    | <LESS_THAN_EQUAL_TO>
    | <GREATER_THAN_EQUAL_TO>
    | <LESS_THAN>
    | <GREATER_THAN> | <NOT>) RHS_prime()
|   expression() RHS_prime()
|   <SEMICOLON>
|   complex() RHS_prime() {System.out.println("entered complex()");}
}

void var():
{}
{
    <NOT> expression()
|   <INTEGER_LITERAL>
|   <IDENTIFIER> (LOOKAHEAD(2) params())?
|   <TRUE>
|   <FALSE>
}

void expression():
{}
{
    <LEFT_PARENTHESIS> expression() <RIGHT_PARENTHESIS> (LOOKAHEAD(2) expression_prime())*
|   LOOKAHEAD(2) args() (LOOKAHEAD(2) expression_prime())*
|   var() (LOOKAHEAD(2) expression_prime())*
}

void expression_prime():
{}
{
    (<PLUS> | <MINUS> | <ASTERISK> | <SLASH> | <AND> | <OR>
    | <LESS_THAN_EQUAL_TO>
    | <GREATER_THAN_EQUAL_TO>
    | <LESS_THAN>
    | <NOT_EQUALS>
    | <GREATER_THAN>
    | <EQUALS_EQUALS>) var() (LOOKAHEAD(2) complex())?
}

void complex():
{}
{
    <PERIOD> var()
|   <LEFT_BRACKET> complex_prime()
|   <RIGHT_BRACKET> (LOOKAHEAD(2) args_p())*
|   <PLUS_PLUS>
|   <MINUS_MINUS>
|   <COMMA>
}

void complex_prime():
{}
{
    expression() complex()
|   <RIGHT_BRACKET>
}
